const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { parseHTML } = require('linkedom');
const root = path.join(__dirname, '..');
function load(file, external, options = {}) {
  const source = fs.readFileSync(path.join(root, file), 'utf8');
  const { document, Event, HTMLElement } = parseHTML(source);
  Object.defineProperty(HTMLElement.prototype, 'innerText', {get(){return this.textContent;},set(v){this.textContent=String(v);}, configurable:true});
  const timers = new Map(), alerts = [], events = {}, storage = new Map(Object.entries(options.storage || {}));
  let next=1, now=1000, seed=123;
  const random = () => {seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  const canvasContext = new Proxy({}, {get:(_,k)=>k==='measureText'?s=>({width:String(s).length*8}):()=>{},set:()=>true});
  for(const canvas of document.querySelectorAll('canvas')) canvas.getContext=()=>canvasContext;
  const window={addEventListener(type,cb){(events[type] ||= []).push(cb);}};
  if(!options.noAudio) window.AudioContext=class {currentTime=0;state='running';destination={};resume(){return Promise.resolve();}createOscillator(){return {frequency:{},connect(){},start(){},stop(){}};}createGain(){return {gain:{exponentialRampToValueAtTime(){}},connect(){}};}};
  const context=vm.createContext({document,window,Event,console, Math:Object.assign(Object.create(Math),{random}),
    Date:class extends Date {static now(){return now;}},performance:{now:()=>now},
    localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v))},alert:s=>alerts.push(s),
    setTimeout(cb,ms){const id=next++;timers.set(id,{cb,ms,repeat:false});return id;},clearTimeout:id=>timers.delete(id),
    setInterval(cb,ms){const id=next++;timers.set(id,{cb,ms,repeat:true});return id;},clearInterval:id=>timers.delete(id),
    requestAnimationFrame(cb){const id=next++;timers.set(id,{cb:()=>cb(now),ms:16,repeat:false});return id;},cancelAnimationFrame:id=>timers.delete(id)});
  const run=js=>vm.runInContext(js,context,{timeout:5000});
  for(const m of source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))run(m[1]);
  if(external)run(fs.readFileSync(path.join(root,external),'utf8'));
  return {document,Event,run,context,timers,alerts,events,storage,
    tick(ms){now+=ms;for(const [id,t] of [...timers])if(t.ms===ms&&timers.has(id)){if(!t.repeat)timers.delete(id);t.cb();}},
    click(selector){const el=typeof selector==='string'?document.querySelector(selector):selector;el.dispatchEvent(new Event('click',{bubbles:true}));},
    key(key,extra={}){const e=new Event('keydown',{bubbles:true,cancelable:true});Object.assign(e,{key,...extra});document.dispatchEvent(e);for(const cb of events.keydown||[])cb(e);return e;}
  };
}
const boardPaths={simon:'gry/simon/simon.html',saper:'gry/saper/saper.html',chess:'gry/chess/chess.html',connect4:'gry/connect4/connect4.html',wordle:'gry/wordle/wordle.html',sudoku:'gry/sudoku/sudoku.html',pasjans:'gry/pasjans/pasjans.html',memory:'gry/gra zapamietywanie/gra zapamietywanie.html',ttt:'gry/kolkokrzyrzykc/kolkokrzyzykc.html',kolkos:'gry/kolkos/kolkos.html',hangman:'gry/wisielec/wisielec.html'};
const game=name=>load(boardPaths[name]);
test('Simon: repeated start leaves one playback timer and no stale next round',()=>{const p=game('simon');p.run('startGame();startGame()');assert.equal(p.timers.size,1);p.tick(800);p.run('userClick(sequence[0]);startGame()');p.tick(1000);assert.equal(p.run('sequence.length'),1);});
test('Simon: silent devices can start and play',()=>{const p=load(boardPaths.simon,null,{noAudio:true});p.run('startGame()');p.tick(800);assert.equal(p.run('turn'),'user');});
test('Saper: all eight neighbors are counted at every edge',()=>{const p=game('saper');p.run('width=3;height=3;bombAmount=1;createBoard()');for(let bomb=0;bomb<9;bomb++){p.run(`squares.forEach((s,i)=>s.dataset.type=i===${bomb}?'bomb':'valid');calculateNumbers()`);for(let i=0;i<9;i++)if(i!==bomb){const expected=+(Math.abs(i%3-bomb%3)<=1&&Math.abs(Math.floor(i/3)-Math.floor(bomb/3))<=1);assert.equal(p.run(`Number(squares[${i}].getAttribute('data'))`),expected);}}});
test('Saper: flag at the limit can still be removed',()=>{const p=game('saper');p.run("squares.forEach(s=>s.dataset.type='valid');for(let i=0;i<bombAmount;i++)addFlag(squares[i]);addFlag(squares[0])");assert.equal(p.run('flags'),9);});
test('Saper: flood reveal cannot touch a new board and timer resets immediately',()=>{const p=game('saper');p.run("squares.forEach(s=>{s.dataset.type='valid';s.setAttribute('data',0)});click(squares[0]);timerEl.innerText='020';createBoard()");p.tick(10);assert.equal(p.document.querySelectorAll('.revealed').length,0);assert.equal(p.document.getElementById('timer').textContent,'000');});
test('Saper: revealing every safe cell wins without flags',()=>{const p=game('saper');p.run("squares.forEach(s=>{if(s.dataset.type==='valid')s.classList.add('revealed')});checkForWin()");assert.equal(p.run('isGameOver'),true);});
test('Chess: reset cancels pending AI and mode change needs no global event',()=>{const p=game('chess');p.run("gameMode='ai';handleSquareClick(6,0);handleSquareClick(4,0);resetGame()");const before=p.run('JSON.stringify(board)');p.tick(500);assert.equal(p.run('JSON.stringify(board)'),before);assert.doesNotThrow(()=>p.run("setMode('pvp')"));});
test('Chess: repeated reset as black schedules just one opening AI move',()=>{const p=game('chess');p.run("gameMode='ai';playerColor='black';resetGame();resetGame();resetGame()");assert.equal(p.timers.size,1);p.tick(500);assert.equal(p.run('currentPlayer'),'black');});
test('Chess: promotion locks board input until a piece is chosen',()=>{const p=game('chess');p.run("pendingPromotion={row:0,col:0,color:'white'};handleSquareClick(6,0)");assert.equal(p.run('selectedPiece'),null);});
test('Connect4: a full draw ends the round and restart clears it',()=>{const p=game('connect4');p.run('board=Array.from({length:7},(_,c)=>Array.from({length:6},(_,r)=>((Math.floor(c/2)+r)%2)+1));board[6][5]=0;currentPlayer=1;dropToken(6)');assert.equal(p.run('gameOver'),true);assert.match(p.document.querySelector('.status').textContent,/Remis/);p.run('resetGame()');assert.equal(p.run('gameOver'),false);assert.equal(p.run('board.flat().filter(Boolean).length'),0);});
test('Solitaire: new deal clears selected waste card before a move',()=>{const p=game('pasjans');p.run("drawCard();selected={type:'waste',index:0,cardIndex:0};initGame()");assert.equal(p.run('selected'),null);assert.doesNotThrow(()=>p.run('attemptMoveToPile(0);attemptMoveToFoundation(0)'));});
test('Memory: preview blocks guesses; reset cancels old mismatch callback',()=>{const p=game('memory');const cards=[...p.document.querySelectorAll('[data-card]')];p.click(cards[0]);assert.equal(p.document.querySelector('[data-memory-moves]').textContent,'0');assert.equal(p.timers.size,1);p.tick(1800);p.click(cards[0]);const different=cards.find(c=>c.dataset.color!==cards[0].dataset.color);p.click(different);p.click('[data-memory-reset]');p.tick(1800);p.click(cards[0]);p.tick(750);assert.equal(cards[0].classList.contains('hidden'),false);});
test('Memory: malformed saved result does not crash startup',()=>{assert.doesNotThrow(()=>load(boardPaths.memory,null,{storage:{'memory-best-score':'{}'}}));});
test('Tic-tac-toe: restarting while AI thinks cannot place a stale move',()=>{const p=game('ttt');p.click('[data-mode="ai"]');p.click('[data-cell]');p.click('[data-action="reset"]');p.tick(500);assert.equal([...p.document.querySelectorAll('[data-cell]')].filter(c=>c.textContent).length,0);});
test('Hangman: game over freezes keyboard guesses and score',()=>{const p=game('hangman');for(const letter of 'ABCDEFGHIJKLMNOPQRSTUVWXYZĄĆĘŁŃÓŚŹŻ')p.key(letter);const losses=p.document.querySelector('[data-hangman-mistakes]').textContent,wins=p.document.querySelector('[data-hangman-wins]').textContent;assert.ok(+losses<=+p.document.querySelector('[data-hangman-max]').textContent);p.key('Z');assert.equal(p.document.querySelector('[data-hangman-wins]').textContent,wins);assert.equal(p.document.querySelectorAll('[data-hangman-keyboard] button:not([disabled])').length,0);});
test('Quiz: many-question mode starts once and can finish/restart',()=>{const p=load('gry/quiz/play.html','gry/quiz/script.js');p.click('#multiple-questions');assert.equal(p.document.querySelectorAll('#quiz-page h2').length,1);p.run('while(currentQuestionIndex<activeQuestions.length){checkAnswerMultiple(activeQuestions[currentQuestionIndex].correct);if(currentQuestionIndex<activeQuestions.length)displayNextQuestion()}');assert.equal(p.document.getElementById('result-page').classList.contains('hidden'),false);p.run('restartQuiz()');assert.equal(p.document.getElementById('quiz-page').classList.contains('hidden'),false);});
test('Wheel: starts without CDN, ignores empty spins and reset cancels animation',()=>{const p=load('gry/kolo_fortuny/play.html','gry/kolo_fortuny/script.js');p.click('.spin-trigger');assert.equal(p.timers.size,0);const input=p.document.querySelector('.joiner');input.value='<img src=x onerror=alert(1)>';p.click('.add');assert.equal(p.document.querySelector('.participants li').textContent,input.value||'<img src=x onerror=alert(1)>');assert.equal(p.document.querySelector('.participants img'),null);p.click('.spin-trigger');p.click('.spin-trigger');assert.equal(p.timers.size,1);p.click('.reset');assert.equal(p.timers.size,0);assert.equal(p.document.querySelectorAll('.participants li').length,0);});
test('Wordle: repeated-letter feedback consumes each secret letter once',()=>{const p=game('wordle');p.run("secret='ALARM';'AAAAA'.split('').forEach(type);submit()");for(const ms of [0,200,400,600,800])p.tick(ms);assert.equal(p.document.querySelectorAll('.tile.correct').length,2);assert.equal(p.document.querySelectorAll('.tile.absent').length,3);assert.ok(p.document.getElementById('key-A').classList.contains('correct'));});
test('Wordle: restart clears delayed results and six rows, while shortcuts do not type',()=>{const p=game('wordle');p.run("secret='ALARM';'ALARM'.split('').forEach(type);submit();resetGame()");assert.equal(p.timers.size,0);assert.equal(p.document.querySelectorAll('.tile').length,30);p.key('a',{ctrlKey:true});assert.equal(p.run('currentCol'),0);p.key('a');assert.equal(p.run('currentCol'),1);assert.equal(p.key('Backspace').defaultPrevented,true);assert.equal(p.run('currentCol'),0);});
test('Wordle: sixth failed guess ends safely and all on-screen keys are buttons',()=>{const p=game('wordle');p.run("secret='ALARM';for(let i=0;i<6;i++){'ZZZZZ'.split('').forEach(type);submit()}type('A');backspace();submit()");assert.equal(p.run('gameOver'),true);assert.equal(p.run('currentRow'),6);assert.equal(p.document.querySelectorAll('.keyboard button').length,28);});
test('Sudoku: seeded puzzles have one solution and input rejects non-digits/zero',()=>{const p=game('sudoku');for(let i=0;i<4;i++){p.run('newGame()');assert.equal(p.run("countSolutions([...document.querySelectorAll('.cell')].map(c=>Number(c.value)||0),2)"),1);assert.equal(p.run("solution.every(Boolean)"),true);}const editable=[...p.document.querySelectorAll('.cell')].find(c=>!c.readOnly);editable.value='0e-72';editable.dispatchEvent(new p.Event('input',{bubbles:true}));assert.equal(editable.value,'7');});
test('Sudoku: complete solution succeeds and new game does not duplicate cells',()=>{const p=game('sudoku');p.run("document.querySelectorAll('.cell').forEach((c,i)=>c.value=solution[i]);check();newGame();newGame()");assert.match(p.alerts[0],/Gratulacje/);assert.equal(p.document.querySelectorAll('.cell').length,81);});
test('Saper: first revealed mine is relocated with mine count preserved; touch flag mode toggles',()=>{const p=game('saper');p.run("click(squares.find(s=>s.dataset.type==='bomb'))");assert.equal(p.run('isGameOver'),false);assert.equal(p.run("squares.filter(s=>s.dataset.type==='bomb').length"),10);p.run('createBoard()');p.click('#flag-mode');p.click('.cell');assert.equal(p.run('flags'),1);p.click('.cell');assert.equal(p.run('flags'),0);assert.equal(p.document.getElementById('flag-mode').getAttribute('aria-pressed'),'true');});
test('Chess: pawn attacks, castling and king captures use legal constraints',()=>{const p=game('chess');p.run("board.forEach(row=>row.fill(null));board[7][4]={type:'king',color:'white',hasMoved:false};board[7][7]={type:'rook',color:'white',hasMoved:false};board[0][4]={type:'king',color:'black',hasMoved:false};board[6][4]={type:'pawn',color:'black',hasMoved:true}");assert.equal(p.run("isSquareUnderAttack(7,5,'black')"),true);assert.equal(p.run("isSquareUnderAttack(7,4,'black')"),false);assert.equal(p.run('isValidMove(7,4,7,6)'),false);p.run("board[6][4]=null;board[6][0]={type:'rook',color:'white',hasMoved:false};board[0][0]={type:'king',color:'black',hasMoved:false}");assert.equal(p.run('isValidMove(6,0,0,0)'),false);});
test('Chess: a basic legal human and AI move preserve 32 pieces',()=>{const p=game('chess');p.run("setMode('ai');handleSquareClick(6,4);handleSquareClick(4,4)");assert.equal(p.run('currentPlayer'),'black');p.tick(500);assert.equal(p.run('currentPlayer'),'white');assert.equal(p.run('board.flat().filter(Boolean).length'),32);});
test('Connect4: legal horizontal win freezes turns and full columns reject drops',()=>{const p=game('connect4');p.run('[0,0,1,1,2,2,3].forEach(dropToken)');assert.equal(p.run('gameOver'),true);assert.match(p.document.querySelector('.status').textContent,/Czerwony/);const before=p.run('JSON.stringify(board)');p.run('dropToken(4)');assert.equal(p.run('JSON.stringify(board)'),before);p.run('resetGame();for(let i=0;i<7;i++)dropToken(0)');assert.equal(p.run('board[0].filter(Boolean).length'),6);});
test('Solitaire: deals preserve 52 cards and valid foundation moves flip newly exposed card',()=>{const p=game('pasjans');assert.equal(p.run('stock.length+piles.flat().length'),52);p.run("piles[0]=[{...createCard('♣','2'),faceUp:false},{...createCard('♥','A'),faceUp:true}];selected={type:'pile',index:0,cardIndex:1};attemptMoveToFoundation(0)");assert.equal(p.run('foundations[0][0].value'),'A');assert.equal(p.run('piles[0][0].faceUp'),true);});
test('Memory: matching all nine pairs stops timer and reports 100% accuracy',()=>{const p=game('memory');p.tick(1800);const cards=[...p.document.querySelectorAll('[data-card]')];const colors=[...new Set(cards.map(c=>c.dataset.color))];for(const color of colors)for(const card of cards.filter(c=>c.dataset.color===color))p.click(card);assert.equal(p.document.querySelector('[data-memory-accuracy]').textContent,'100%');assert.match(p.document.querySelector('[data-memory-message]').textContent,/Gratulacje/);assert.equal(p.timers.size,0);});
test('Tic-tac-toe: hard AI never loses from any human reply',()=>{const paths=[[]];let completed=0;const p=game('ttt');p.click('[data-mode="ai"]');while(paths.length){const moves=paths.pop();p.click('[data-action="reset"]');for(const i of moves){p.click(p.document.querySelectorAll('[data-cell]')[i]);p.tick(500);}const cells=[...p.document.querySelectorAll('[data-cell]')];if(cells.every(c=>c.disabled)){assert.equal(p.document.querySelector('[data-score-x]').textContent,'0');completed++;continue;}for(let i=0;i<9;i++)if(!cells[i].textContent)paths.push([...moves,i]);}assert.ok(completed>100);});
test('Legacy Kolkos: AI timer cancels on restart and human cannot play its turn',()=>{const p=game('kolkos');p.click('[data-cell]');p.click(p.document.querySelectorAll('[data-cell]')[1]);assert.equal([...p.document.querySelectorAll('[data-cell]')].filter(c=>c.textContent).length,1);p.click('[data-action="reset"]');p.tick(450);assert.equal([...p.document.querySelectorAll('[data-cell]')].filter(c=>c.textContent).length,0);});
test('Quiz: duplicate answer cannot increase score or advance twice',()=>{const p=load('gry/quiz/play.html','gry/quiz/script.js');p.click('#multiple-questions');p.run('checkAnswerMultiple(activeQuestions[0].correct);checkAnswerMultiple(activeQuestions[0].correct)');assert.equal(p.run('score'),1);assert.equal(p.run('currentQuestionIndex'),1);assert.equal(p.run('activeQuestions.length'),10);p.run('returnToStart();checkAnswerMultiple(0)');assert.equal(p.run('currentQuestionIndex'),1);});
test('Wheel: a completed spin picks an existing participant and permits another round',()=>{const p=load('gry/kolo_fortuny/play.html','gry/kolo_fortuny/script.js');for(const name of ['Ala','Ola','Ela']){p.document.querySelector('.joiner').value=name;p.click('.add');}p.click('.spin-trigger');for(let i=0;i<250;i++)p.tick(16);assert.match(p.document.querySelector('.winner').textContent,/^Wylosowano: (Ala|Ola|Ela)$/);assert.equal(p.timers.size,0);assert.equal(p.document.querySelector('.spin-trigger').disabled,false);p.click('.spin-trigger');assert.equal(p.timers.size,1);});
test('Solitaire: a foundation top card can return to a legal tableau pile',()=>{const p=game('pasjans');p.run("foundations[0]=[{...createCard('♥','A'),faceUp:true}];piles[0]=[{...createCard('♣','2'),faceUp:true}];clickFoundation(0);attemptMoveToPile(0)");assert.equal(p.run('foundations[0].length'),0);assert.equal(p.run('piles[0][1].value'),'A');});
test('Chess: a pinned rook cannot expose its king; normal castling moves both pieces',()=>{const p=game('chess');p.run("board.forEach(row=>row.fill(null));board[7][4]={type:'king',color:'white',symbol:pieces.white.king,hasMoved:false};board[6][4]={type:'rook',color:'white',symbol:pieces.white.rook,hasMoved:false};board[0][4]={type:'rook',color:'black',symbol:pieces.black.rook,hasMoved:false};board[0][0]={type:'king',color:'black',symbol:pieces.black.king,hasMoved:false}");assert.equal(p.run('isValidMove(6,4,6,3)'),false);p.run("board[0][4]=null;board[6][4]=null;board[7][7]={type:'rook',color:'white',symbol:pieces.white.rook,hasMoved:false};handleSquareClick(7,4);handleSquareClick(7,6)");assert.equal(p.run('board[7][6].type'),'king');assert.equal(p.run('board[7][5].type'),'rook');});
