const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const {parseHTML}=require('linkedom');
function load(data) {
 const root=path.join(__dirname,'..'); const {document,Event}=parseHTML(fs.readFileSync(path.join(root,'LinkHub/index.html'),'utf8'));
 const ctx=vm.createContext({document,URL,console});
 vm.runInContext(data || fs.readFileSync(path.join(root,'LinkHub/data.js'),'utf8'),ctx);
 vm.runInContext(fs.readFileSync(path.join(root,'LinkHub/app.js'),'utf8'),ctx);
 return {document,click:selector=>document.querySelector(selector).dispatchEvent(new Event('click')),search:value=>{document.getElementById('search-input').value=value;document.getElementById('search-input').dispatchEvent(new Event('input'));}};
}
test('LinkHub bounds initial render and loads more without losing the database',()=>{const p=load();assert.equal(p.document.querySelectorAll('#links-container a').length,60);assert.match(p.document.getElementById('search-stats').textContent,/5529/);p.click('#links-more');assert.equal(p.document.querySelectorAll('#links-container a').length,120);});
test('LinkHub search remains applied in history and restores selected category',()=>{const p=load();p.click('[data-category="ai"]');p.search('openai');assert.equal(p.document.querySelectorAll('#links-container a').length,3);p.click('[data-view="timeline"]');assert.equal(p.document.querySelectorAll('#links-container a').length,3);assert.equal(p.document.querySelectorAll('.timeline-item').length,3);p.search('no-such-link-123');assert.equal(p.document.querySelectorAll('#links-container a').length,0);assert.match(p.document.getElementById('links-container').textContent,/Brak wyników/);p.search('openai');p.click('[data-view="categories"]');assert.equal(p.document.querySelector('[data-category="ai"]').getAttribute('aria-pressed'),'true');assert.equal(p.document.querySelectorAll('#links-container a').length,3);});
test('LinkHub search and record text are literal and unsafe URLs never execute',()=>{const p=load('const LINKHUB_LINKS=[{name:"<img src=x onerror=alert(1)>",url:"javascript:alert(1)",description:"<b>hello</b>",category:"x"}];const LINKHUB_CATEGORIES={x:{name:"<script>evil</script>",color:"red;display:none"}};');assert.equal(p.document.querySelector('#links-container img'),null);assert.equal(p.document.querySelector('#links-container script'),null);assert.equal(p.document.querySelector('#links-container a').getAttribute('href'),'#');assert.match(p.document.getElementById('links-container').textContent,/<b>hello<\/b>/);p.search('<img src=x onerror=alert(1)>missing');assert.equal(p.document.querySelector('#links-container img'),null);assert.match(p.document.getElementById('links-container').textContent,/<img/);});
test('LinkHub history is newest first and filtering resets pagination',()=>{const p=load('const LINKHUB_LINKS=Array.from({length:140},(_,i)=>({name:"item"+i,url:"https://example.com/"+i,category:i<70?"a":"b",added:String(1000+i)}));const LINKHUB_CATEGORIES={};');p.click('#links-more');p.click('[data-category="b"]');assert.equal(p.document.querySelectorAll('#links-container a').length,60);p.click('[data-view="timeline"]');assert.match(p.document.querySelector('#links-container a').textContent,/item139/);p.search('item139');assert.equal(p.document.querySelectorAll('#links-container a').length,1);assert.equal(p.document.getElementById('links-more').hidden,true);});
